ALTER TABLE posts
ADD COLUMN latitude DECIMAL(9,6),
ADD COLUMN longitude DECIMAL(9,6),
ADD COLUMN bird_id BIGINT REFERENCES birds(id) ON UPDATE CASCADE,
ADD COLUMN user_img VARCHAR(100),
ADD COLUMN date_of_sighting DATE,
ADD COLUMN created_at TIMESTAMP,
ADD COLUMN enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN restricted BOOLEAN;

